# Generated by Django 3.2.4 on 2021-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imageUrl', models.CharField(max_length=500)),
                ('isAvailable', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('authors', models.ManyToManyField(to='bookfarm.Author')),
                ('tags', models.ManyToManyField(to='bookfarm.Tag')),
            ],
        ),
    ]
